image: gitpod/workspace-full-vnc
ports:
- name: GenomeAssembly
  port: 3000
  onOpen: open-browser
  visibility: public

tasks:
- name: SETUP ENVIRONMENT
  init: |
    mkdir -p /workspace/bin
    cd /workspace
    # MAMBA
    wget "https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Mambaforge-24.3.0-0-Linux-x86_64.sh"
    bash Mambaforge-24.3.0-0-Linux-x86_64.sh -b -p /workspace/mambaforge && rm Mambaforge-24.3.0-0-Linux-x86_64.sh

    /workspace/mambaforge/bin/mamba init bash
    source ${HOME}/.bashrc

    conda config --add channels defaults
    conda config --add channels bioconda
    conda config --add channels conda-forge
    conda config --set channel_priority strict

    mamba install -y minimap2 bwa-mem2 samtools gnuplot bedtools gfastats pretext-suite
    pip install numpy pandas

    # SMUDGEPLOT
    cd /workspace
    git clone -b sploidyplot https://github.com/KamilSJaron/smudgeplot
    cd /workspace/smudgeplot
    make -s INSTALL_PREFIX=/workspace

    # FASTK
    cd /workspace
    git clone https://github.com/thegenemyers/FastK
    cd /workspace/FastK && make -s INSTALL_PREFIX=/workspace
    install -c FastK Fastrm Fastmv Fastcp Fastmerge Histex Tabex Profex Logex Vennex Symmex Haplex Homex Fastcat /workspace/bin/

    # MERQURY.FK
    cd /workspace
    git clone https://github.com/thegenemyers/MERQURY.FK
    cd /workspace/MERQURY.FK && make -s INSTALL_PREFIX=/workspace
    install -c ASMplot blk_plot.R.h CNplot cn_plot.R.h HAPmaker HAPplot hap_plot.R.h KatComp KatGC kgc_plot.R.h kx_plot.R.h MerquryFK PloidyPlot smu_plot.R.h /workspace/bin/

    # YAHS
    cd /workspace
    git clone https://github.com/c-zhou/yahs
    cd /workspace/yahs && make -s INSTALL_PREFIX=/workspace
    install -c agp_to_fasta yahs juicer /workspace/bin

    export PATH=$PATH:/workspace/bin

    gp sync-done bundle

    # Get Data
    mkdir -p /workspace/data
    
workspaceLocation: "/workspace"
