image: gitpod/workspace-full-vnc
ports:
- name: GenomeAssembly
  port: 3000
  onOpen: open-browser
  visibility: public


tasks:
  - name: SETUP - Install Nextflow
  # https://www.nextflow.io/docs/latest/getstarted.html
    init: |
      cd /workspace/treeval-curation/
      
      wget -qO- https://get.nextflow.io | bash

      chmod +x nextflow

      sudo mv nextflow /usr/local/bin

workspaceLocation: "/workspace"